#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [ ! -f ~/.shell_modifications ]; then
  touch ~/.shell_modifications
fi
setopt clobber
setopt hist_ignore_dups
unsetopt extended_glob
unsetopt share_history
source ~/.shell_modifications
